site_name: StarMod Project
site_author: Ewoud Wijma (ewowi)
#site_url: https://starmod.app
repo_name: StarMod
repo_url: https://github.com/ewowi/StarMod
repo_title: StarMod Repository
#copyright: Copyright &copy; 2016-2024 MoonModules, Contributors
edit_uri: https://github.com/ewowi/StarDocs/edit/main/docs
theme:
  name: material
  custom_dir: docs/assets/overrides
  language: en
  favicon: assets/images/ui/aircoookie/blurple.png
  logo: assets/images/ui/starmod/moonmodules.png
  icon: 
    repo: fontawesome/brands/github
  features: 
    - navigation.top
    # - navigation.expand
    - navigation.instant
    - navigation.tabs
    - content.action.edit
    # - toc.integrate
  palette:
    - scheme: starmod
      primary: cyan #mostly overriden in extra.css
      accent: orange
      toggle: 
        icon: material/weather-sunny
        name: Light Mode
    - scheme: default
      primary: orange
      accent: orange
      toggle: 
        icon: material/weather-night
        name: Dark Mode
plugins: 
  - search
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tilde
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/K9JBvgNG
      name: Discord SR
    - icon: fontawesome/brands/discourse
      link: https://starmod.discourse.group/
      name: Forum
    - icon: fontawesome/solid/code
      link: https://gitpod.io/#https://github.com/ewowi/StarMod
      name: Gitpod
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/starmod_project/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/results?search_query=StarMod
    - icon: fontawesome/solid/shirt
      link: https://starmod.teemill.com/
    - icon: fontawesome/solid/heart
      link: https://paypal.me/moonmodules/
extra_css:
  - assets/stylesheets/global.css
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/js/newtab.js
nav:
  - Home: 
    - Welcome: index.md
    - News: news.md
  - StarMod Basics:
    - Getting started: BasicsStarMod/GettingStarted.md
    - Contribute: BasicsStarMod/Contribute.md
    - Testing: BasicsStarMod/Testing.md
    - Development: BasicsStarMod/Development.md
    - Standards and Guidelines: BasicsStarMod/StandardsAndGuidelines.md
  - StarMod Modules:
    - SysMod Overview: SysMod/SysModOverview.md
    - Print Module: SysMod/SysModPrint.md
    - Files Module: SysMod/SysModFiles.md
    - System Module: SysMod/SysModSystem.md
    - Instances Module: SysMod/SysModInstances.md
    - Model Module: SysMod/SysModModel.md
    - Modules Module: SysMod/SysModModules.md
    - Network Module: SysMod/SysModNetwork.md
    - Pins Module: SysMod/SysModPins.md
    - UI Module: SysMod/SysModUI.md
    - Web Module: SysMod/SysModWeb.md
  - StarLeds:
    - Overview: BasicsLed/Overview.md 
    - Getting started: BasicsLed/GettingStarted.md
    - Effects: BasicsLed/Effects.md
    - Projections and Mappings: BasicsLed/ProjectionsAndMappings.md
    - Gallery: BasicsLed/Gallery.md
  - StarLeds Modules:
    - Fixture Generator Module: LedMod/LedModFixture Generator.md
    - Effects Module: LedMod/LedModEffects.md
    - Fixture Module: LedMod/LedModFixture.md
  - User Modules:
    - UserMod overview: UserMod/UserModOverview.md
    - E131-sACN Module: UserMod/UserModE131-sACN.md
    - Artnet Module: UserMod/UserModArtNet.md
    - DDP Module: UserMod/UserModDDP.md
    - MDNS Module: UserMod/UserModMDNS.md
  - About: 
    - Contributors & Credits: about/contributors.md
    - Privacy Policy: about/privacy-policy.md
    - Upcoming Features: about/roadmap.md
    - MoonModules:
      - What is MoonModules: archive/moonmodules/what-is-moonmodules.md
      - Release notes v0.14.0-b3-daily: archive/moonmodules/release-notes-v0.14.0-b3-daily.md
      - Release notes v0.14.0-b25: archive/moonmodules/release-notes-v0.14.0-b25.md
      - Release notes v0.14.0-b15: archive/moonmodules/release-notes-v0.14.0-b15.md
      - Release notes v0.14.0-b1: archive/moonmodules/release-notes-v0.14.0-b1.md
      - Release notes v0.14.0-b0: archive/moonmodules/release-notes-v0.14.0-b0.md
      - Fork comparison: archive/moonmodules/fork-comparison.md
      - Installing and Compiling: archive/moonmodules/Installing-and-Compiling.md
      - Mappings: archive/moonmodules/mappings.md
      - ARTI-FX: archive/moonmodules/arti-fx.md
      - Platformio entries: archive/moonmodules/platformio-entries.md
      - Preset API commands: archive/moonmodules/preset-api-commands.md
      - Contribute to docs: archive/moonmodules/contribute-docs.md
      - Contribute to development: archive/moonmodules/contribute-dev.md